root = "."

[build]
cmd = "go build -buildvcs=false -o /tmp/traefikofficer ./pkg"
bin = "/tmp/traefikofficer"
args_bin = [
    "--config-file=/config/traefik_officer.json",
    "--debug",
    "--use-k8s=true",
    "--kubeconfig=/root/.kube/config",
    "--kube-context=kahf-infra-non-production-k8s-cluster",
    "--namespace=ingress-controller",
    "--container-name=traefik",
    "--listen-port=9090",
    "--pod-label-selector=app.kubernetes.io/name=traefik"
]
include_ext = ["go"]
exclude_dir = ["tmp"]
include_dir = ["pkg", "test"]
delay = 1000