root = "."

[build]
cmd = "go build -o /tmp/traefikofficer ./pkg"
bin = "/tmp/traefikofficer"
args_bin = [
    "--log-file=/var/log/traefik/access.log",
    "--listen-port=8084",
    "--config-file=/config/traefik_officer.json",
    "--max-accesslog-size=50",
    "--debug"
]
include_ext = ["go"]
exclude_dir = ["tmp"]
include_dir = ["pkg"]
delay = 1000